name: Code CI

on:
  push:
  pull_request:
  schedule:
    # Run every Monday at 8am to check latest versions of dependencies
    - cron: "0 8 * * WED"
env:
  # the target python version. Make sure the Dockerfile uses the same
  # version for its build and runtime targets.
  PYTHON: "3.10"

jobs:
  lint:
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON}}

      - name: Lint
        run: |
          touch requirements_dev.txt requirements.txt
          pip install -r requirements.txt -r requirements_dev.txt -e .[dev]
          tox -e pre-commit,mypy

  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # can add windows-latest, macos-latest
        python: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}
    env:
      # https://github.com/pytest-dev/pytest/issues/2042
      PY_IGNORE_IMPORTMISMATCH: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install with latest dependencies
        run: |
          pip install .[dev]
          mkdir -p lockfiles
          pip freeze > lockfiles/requirements-dev-py${{ matrix.python }}.txt

      - name: Run tests
        run: pytest tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.python }}/${{ matrix.os }}
          files: cov.xml

      - name: Upload lock files
        uses: actions/upload-artifact@v3
        with:
          name: lockfiles
          path: lockfiles

  dist:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON}}

      - name: Build Sdist and wheel
        run: |
          export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct) && \
          pipx run --python $(which python${{env.PYTHON}}) build

      # ${GITHUB_REPOSITORY##*/} is the repo name without org
      # Replace this with the cli command if different to the repo name
      - name: Test cli works in sdist installed in local python
        run: |
          touch requirements.txt
          pip install -r requirements.txt dist/*.gz ${GITHUB_REPOSITORY##*/} --version

      # create a requirements.txt to be published as a github release asset
      - name: get a requirements.txt from the installed sdist
        run: |
          mkdir -p lockfiles
          pip freeze > lockfiles/requirements.txt

      - name: Upload sdist and wheel as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

      - name: Upload lock files
        uses: actions/upload-artifact@v3
        with:
          name: lockfiles
          path: lockfiles

  container:
    needs: [dist]
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{env.IMAGE_REPOSITORY}}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build runtime image
        uses: docker/build-push-action@v3
        with:
          push: true
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          context: .

      - name: Test cli works in runtime image
        # check that the first tag can run with --version parameter
        run: docker run ${{env.IMAGE_REPOSITORY}}:latest --version

      # TODO upload a tar of the image for later publishing
      # TODO OR do the publish here ??? if its quick enough - MUCH easier ?

  release:
    # upload to PyPI and make a release on every tag
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [lint, dist]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3

      - name: fixup requirements files
        # use sed to comment out the self references in requirements files
        run: sed -i '/file:/s/^/# Requirements for /' lockfiles/requirements*.txt

      - name: Github Release
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v0.1.14
        with:
          prerelease: ${{ contains(github.ref_name, 'a') || contains(github.ref_name, 'b') || contains(github.ref_name, 'rc') }}
          files: |
            dist/*
            lockfiles/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
